### PR TITLE
Add Age-Calculator and README.md file

### PR DESCRIPTION
**Pull request by Suryansh1720001**
# Age Calculator
Age-Calculator is a kotlin based android application

## Tech

- Kotlin language
- xml language
- Android Studio

### CODE REVIEW

**Comment by aadityamp01** [comment]
Hey @Suryansh1720001 
your app is not visible in changes please check 
https://github.com/aadityamp01/Androapps/pull/109/files

**Comment by Suryansh1720001** [comment]
Hello @aadityamp01 
Yes, that was the issue of the submodule. Now Please check the changed files will show there only.
Thank you

**Comment by Suryansh1720001** [comment]
Hello @aadityamp01 
Please merge it, if you satisfy with this.
Thank you

**Review by aadityamp01 — APPROVED** [review]

**Comment by aadityamp01** [comment]
Hey @Suryansh1720001 
Thanks for your contribution into Androapps!

**Pull request merged**
