### PR TITLE
Greeting Card App

### LINKED ISSUE #54: Simple Greeting Card App
With this app beginners can learn about UI, Intent.

Please Assign it to me, Thanks

### PR DESCRIPTION
**Pull request by akshatbhuhagal**
# Greeting Card App

This App shows how to use Intent to send data & switch between different activities, Best way to learn Intent, Lottie Animation through this App.

Fixes #54 

### Type of Change:
- Android application added

### Checklist:

- [ ✔ ] My PR follows the style guidelines of this project
- [ ✔ ] I have performed a self-review of my own code or materials
- [ ✔ ] My branch is up-to-date with the Upstream development branch
- [ ✔ ] I have added necessary images/screenshots of my changes

### CODE REVIEW

**Comment by akshatbhuhagal** [comment]
Also Dont Forget to add label of Hacktoberfest

**Comment by akshatbhuhagal** [comment]
Done conflict resolved
Also add Hacktoberfest tag
Thanks

**Comment by aadityamp01** [comment]
It's not resolved, check again you deleted content of Recyclerview App/readme.md file, donot select/change that file in your current branch.
Don't change other apps, other than yours!

**Comment by aadityamp01** [comment]
Thanks for Contribution @akshatbhuhagal 
Great job! 😀

**Pull request merged**
