### PR TITLE
Added Notes App

### PR DESCRIPTION
**Pull request by sudipbhakat07**
I have added a Notes App, where we can add notes which will be stored in the database and will be displayed in a recycler view. We can update and delete a note, just by clicking on the note from the list.
I have also added the hosted link of the app in the readme.

### Type of Change:
- Android application added

### Checklist:
- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] My branch is up-to-date with the Upstream development branch
- [x] I have added necessary images/screenshots of my changes

SplashScreen
NotesApp1
NotesApp2
NotesApp3
NotesApp4

### CODE REVIEW

**Comment by aadityamp01** [comment]
Hey @sudipbhakat07  Please select all the checkbox!

**Comment by sudipbhakat07** [comment]
> Hey @sudipbhakat07 Please select all the checkbox!

Yeah sure @aadityamp01

**Comment by aadityamp01** [comment]
Hey @sudipbhakat07 your app's looking good to me!
But you're overwriting on other apps/commits, please only add your app with no other changes, refer CONTRIBUTING.md for this, create separate branch and push your changes in minimum commits, refer README.md

**Comment by sudipbhakat07** [comment]
Hey @aadityamp01 sorry for that!
But now I have created another PR with a separate branch and maintaining all the guidelines.
Please merge the PR #24 .
Thank you in advance.

**Pull request closed without merging**
