### PR TITLE
Upgrading Toast View 

### LINKED ISSUE #20: Upgrading Toast View
Fixes Required:
1. The toast we usually see is kinda general and the same for all the situations, so to make it more readable by any individual the toast customization is required.
2. This [Dependency](https://github.com/GrenderG/Toasty.git) can be used.

### PR DESCRIPTION
**Pull request by thisisshivamgupta**
### Description

Fixes #20 

### Type of Change:

- Updated exiting applications

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] My branch is up-to-date with the Upstream development branch
- [x] I have added necessary images/screenshots of my changes

Mandatory Toast
Successful Toast
Warning Toast

### CODE REVIEW

**Comment by aadityamp01** [comment]
Please create an issue first describing about your PR then link this issue here, 
Add follow all points of PR, 
add images of app testing after changing your code.

**Comment by thisisshivamgupta** [comment]
Upgrading Toast View #20 Created the issue!

**Comment by thisisshivamgupta** [comment]
Linked issue #20 to the PR!

**Comment by aadityamp01** [comment]
Hi
You haven't added images of testing and actual working of app, as mentioned above and please go through the README.md , create your commits on separate branch, make sure your project is updated!

**Comment by thisisshivamgupta** [comment]
Thanks, @aadityamp01  Demo images pinned!

**Review by aadityamp01 — APPROVED** [review]

**Comment by aadityamp01** [comment]
@thisisshivamgupta Thanks for your contribution!

**Pull request merged**
