### PR TITLE
Adding Picture Clicking Application

### LINKED ISSUE #84: PictureClickingApp
**Please describe about your Androapp**
1.  An app to click a photo and set it to image view and allow user to download that to phone gallery.
2.  Java

**Describe alternatives you've considered**
No Alternatives

**Additional context**
No additional context.

### PR DESCRIPTION
**Pull request by jmanan088**
### Description

This allows the user to click the photo using camera application and set it to image view. Also gives the user the freedom to download the image.
#### Dependencies Required
- Material Design - 
    implementation 'com.google.android.material:material:1.7.0-alpha03'

Fixes #84 

### Type of Change:
- Android application added

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] My branch is up-to-date with the Upstream development branch
- [x] I have added necessary images/screenshots of my changes

ss1
ss2

### CODE REVIEW

**Comment by aadityamp01** [comment]
Hey @jmanan088 
Your app is good, will merge, just check your app's readme screenshots are not visible properly and update your branch to latest commit of project

**Comment by jmanan088** [comment]
@aadityamp01 please check if this is good. Pictures looks good on my end.

**Comment by aadityamp01** [comment]
Hey!
check your readme, icon in screenshots, it's link is not working and not visible as well
https://github.com/jmanan088/Androapps/blob/picture-clicking-app/Picture%20Clicking%20App/REAMDE.md

**Comment by jmanan088** [comment]
Hey @aadityamp01, thank you for telling me. I resolved that, please check and tell me if there is anything else that needs to be corrected.

**Review by aadityamp01 — APPROVED** [review]

**Comment by aadityamp01** [comment]
Thanks @jmanan088  for your contribution!

**Comment by jmanan088** [comment]
@aadityamp01 can you help me, since this pr is merged it's supposed to show on hacktoberfest page, where it still shows 0/4.

**Pull request merged**
