### PR TITLE
Spotify UI Clone Application

### PR DESCRIPTION
**Pull request by abhayst007**
### Description

Made an android application. It has spotify UI cloned in it with the use of **constraint layout** and **fragments**

Fixes #ISSUE

### Type of Change:

- Android application added
- Updated exiting applications

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] My branch is up-to-date with the Upstream development branch
- [x] I have added necessary images/screenshots of my changes

### CODE REVIEW

**Comment by abhayst007** [comment]
Screenshot_20221014-153207_Spotify_UI_Clone
Screenshot_20221014-153201_Spotify_UI_Clone

**Comment by aadityamp01** [comment]
Hey @abhayst007 
Refer this and add readme into your app folder to describe about your app
https://github.com/aadityamp01/Androapps/blob/master/Password%20Manager/README.md

**Comment by abhayst007** [comment]
@aadityamp01 done can you review the changes

**Comment by aadityamp01** [comment]
Please properly organize your readme images, add dependencies used, requirements, etc.

**Comment by abhayst007** [comment]
I just rearranged the README.md

**Comment by abhayst007** [comment]
can you check it

**Review by aadityamp01 — APPROVED** [review]

**Comment by aadityamp01** [comment]
Hey @abhayst007 
Thanks for your contribution into Androapps!

**Pull request merged**
