### PR TITLE
Added ViewModel Exemplar App for Issue #41

### LINKED ISSUE #41: View Model App
It's an simple number app to increase numbers on click of button using View Model.

With this app folks can learn about View Model.

Please Assigned it to me, Thanks

### PR DESCRIPTION
**Pull request by akshatbhuhagal**
### Description

It's a Exemplar App for showing about How ViewModel works and what's the purpose of ViewModel in Android.

What is ViewModel ? 
Ans : A view model represents the data that you want to display on your view/page, whether it be used for static text or for input values (like textboxes and dropdown lists) that can be added to the database (or edited). It is something different than your domain model. It is a model for the view.

### Type of Change:
- Android application added

### Checklist:

- [ ✔ ] My PR follows the style guidelines of this project
- [ ✔ ] I have performed a self-review of my own code or materials
- [ ✔ ] My branch is up-to-date with the Upstream development branch
- [ ✔ ] I have added necessary images/screenshots of my changes

### CODE REVIEW

**Comment by akshatbhuhagal** [comment]
I will add Readme.md file + screenshots after merging
Thanks

**Comment by aadityamp01** [comment]
1. Please remove .idea folder you pushed/selected, outside your app folder.
2. Please add readme.md and screenshots in the same folder of your app, refer other apps folder for this task!

**Comment by aadityamp01** [comment]
LGTM! 😃
Just link your issue to this PR.
To do this - click edit this comment and write Fixes #issue_number, below your description,
it'll link automatically and close automatically with reference of this PR.

**Comment by aadityamp01** [comment]
Great job @akshatbhuhagal 
Thanks for your contribution!

**Pull request merged**
