### PR TITLE
Added Word Shuffler

### LINKED ISSUE #6: Random Word Shuffler App

### PR DESCRIPTION
**Pull request by xtanion**
### Description

Fixes #6

### Type of Change:

- Android application added
- Updated exiting applications

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] My branch is up-to-date with the Upstream development branch.

### CODE REVIEW

**Comment by xtanion** [comment]
Please check and review my PR, I'll be adding Readme of the App once I finish it entirely.

**Comment by aadityamp01** [comment]
Hey @xtanion you did well just link this PR to the issue so I will review it and add accepted label, 
after Fixes just write #issue_number_only, it will be linked automatically.

**Review by aadityamp01 — APPROVED** [review]

**Comment by aadityamp01** [comment]
Congratulations for merging your first PR
You are welcome to contribute more and help the community to grow!
Thanks!

**Comment by xtanion** [comment]
Thanks, Looking forward to contributing more on Open-source :)

**Pull request merged**
