### PR TITLE
Added Valorant Agents Flutter App

### LINKED ISSUE #74: Create new Mobile App
**Please describe about your Androapp**
1. A clear and concise description about your application and how it'll help to the beginners in android development. Ex. Contributing Calculator app [...]
2. Programming Language 

**Describe alternatives you've considered**

**Additional context**
If possible add any other context or screenshots about the feature request here.

### PR DESCRIPTION
**Pull request by axatabyss**
### Description

This application helps user's to understand about how we can use HTTP library to implement GET api in flutter and to understand about how's api works in Flutter

This app show's Valorant game agents using their official API

Fixes #74 

### Type of Change:
- Flutter mobile application added

### Checklist:

- [✔] My PR follows the style guidelines of this project
- [✔] I have performed a self-review of my own code or materials
- [✔] My branch is up-to-date with the Upstream development branch
- [✔] I have added necessary images/screenshots of my changes

Screenshot_1666200774

### CODE REVIEW

**Comment by axatabyss** [comment]
Please ignore commit from other account because it's messed up on my pc to manage 2 different github accounts

**Comment by aadityamp01** [comment]
Hey you haven't described about your app in readme of app folder, kindly add!
Refer this app 
https://github.com/aadityamp01/Androapps/blob/master/Password%20Manager/README.md

**Comment by aadityamp01** [comment]
Hey you haven't provided any updates, please update or this PR will be closed!

**Comment by aadityamp01** [comment]
Hey closing this PR, if you want to contribute, raise a new PR for this.
Thank you!

**Pull request closed without merging**
