### PR TITLE
Removed all the hard-coded strings from the apps

### LINKED ISSUE #7: Remove hardcoded strings from the apps
To Reproduce

    1. Set up application on your android studio 
    2. Check if it contains any hardcoded strings
    3. Change it by adding into values/strings.xml

Additional context
Make sure to let me know here first so that I can assign this issue to you

### PR DESCRIPTION
**Pull request by gouravkhunger**
### Description

I removed all the hard-coded strings from the apps and added the `.idea` folder to the `.gitignore` so that anyone who tries to run an app doesn't get errors regarding bundled or external JDK. In general, it should be ignored from being pushed.

Fixes #7

### Type of Change:
- Updated exiting applications

### Checklist:

- [x] I have performed a self-review of my own code or materials
- [x] My branch is up-to-date with the Upstream development branch.

### CODE REVIEW

**Comment by aadityamp01** [comment]
Hey you did well, but please remove 
Project.xml, gradle.xml, jarRepositories.xml, runConfigurations.xml, .idea/misc.xml 
these type of files you pushed into the repo, i.e don't push .idea folder files

**Comment by gouravkhunger** [comment]
Yeah that's what I did, there were `.idea` folder files, I have removed them, and also added them to ignore list in the `.gitignore` file.

This red colour means I have deleted them, not added them.

image

**Comment by aadityamp01** [comment]
Hey @gouravkhunger 
Yes I know you are deleting it but it's already there by default and will be deleted from main repo if I merge your commit, so just deselect these files when you are pushing it, 
if you're using Github desktop please refer this screenshot for better idea

Screenshot (426)

**Comment by gouravkhunger** [comment]
Actually the `.idea` folder is not meant to be inside a repo, and it is safe to delete it. 

Also if it is there, then someone who clones the repo and builds the app it can cause some errors, because it contains gradle configuration that are for local setup, and someone's local setup maybe different from others and JDK can conflict. Google says it is safe to delete those files and shouldn't be pushed to repo. 

I am assure that this won't cause any problems I did all the things intentionally and I know what I did. 

It's safe to merge it.

**Review by aadityamp01 — APPROVED** [review]

**Comment by aadityamp01** [comment]
Thanks for your contributions and helpful suggestions @gouravkhunger 
Great job!
You're welcome to contribute more in this project!

**Comment by gouravkhunger** [comment]
Thanks a lot for merging :)

**Pull request merged**
