### PR TITLE
BMI Calculator

### LINKED ISSUE #61: BMI Calculator
## I want to Create an Android app for calculating BMI.

Please assign me!

### PR DESCRIPTION
**Pull request by Anant1711**
### Description

An android app that calculates your BMI.

Fixes #61 

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] My branch is up-to-date with the Upstream development branch
- [x] I have added necessary images/screenshots of my changes

### CODE REVIEW

**Comment by Anant1711** [comment]
@aadityamp01 kindly review my PR!

**Comment by aadityamp01** [comment]
Hey your app looks great, and will be helpful!
Can you add your full project of flutter so we can increase the scope of our repository for beginners,
Also please test your full application is working, and can fit into androapps repository.

After merging this, if you're interested we can update resources in central readme and add more apps possibly with your contributions.
Thanks!

**Comment by Anant1711** [comment]
> Hey your app looks great, and will be helpful! Can you add your full project of flutter so we can increase the scope of our repository for beginners, Also please test your full application is working, and can fit into androapps repository.
> 
> After merging this, if you're interested we can update resources in central readme and add more apps possibly with your contributions. Thanks!

So basically I have to add my full Flutter project, right???
I added androids files because i read the readme.md, that java and Kotlin is allow!
So should i make PR of my whole Flutter project??

**Comment by Anant1711** [comment]
so I'll close this PR now! Okay?
I'm creating new one Right now!

**Comment by aadityamp01** [comment]
Thanks!

**Pull request closed without merging**
