### PR TITLE
Improved Login App

### LINKED ISSUE #12: Improvements in Login App
### Fixes required:
* Once a user is logged in the won't log out if he presses the back button
*  He won't logout even if he closes the app

### PR DESCRIPTION
**Pull request by xtanion**
### Description

Fixes #12 

### Type of Change:

- Android application added
- Updated exiting applications
-  Added Sharedprefrences to save Login Data into app's internal storage
-  UI changes

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] My branch is up-to-date with the Upstream development branch
- [x] I have added necessary images/screenshots of my changes

### CODE REVIEW

**Comment by xtanion** [comment]
Please check and review my PR

**Comment by aadityamp01** [comment]
Please update your repoository and resolve merge conflicts!

**Comment by xtanion** [comment]
@aadityamp01  Fixed merge conflict, please review the changes

**Comment by aadityamp01** [comment]
Hey @xtanion your are overwriting previous commits, 
please make separate branch from your main after updating local changes from upstream,
do your changes then push.

**Pull request closed without merging**
